src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\Column(length: 255)]
    private ?string $capacity = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 50)]
    private ?string $phone_number = null;

    #[ORM\Column(length: 100)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $url = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getCapacity(): ?string
    {
        return $this->capacity;
    }

    public function setCapacity(string $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }
}

src/Controller/EventCrudController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


#[Route('/event')]
class EventCrudController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(ManagerRegistry $doctrine): Response
    {
        $events=$doctrine->getRepository(Event:: class)->findAll();
        // dd($events);
        return $this->render('event_crud/index.html.twig', [
           "events"=>$events
        ]);
    }

// create an event 
    #[Route('/create', name: 'create-event')]
    public function createAction(Request $request, ManagerRegistry $doctrine): Response
    {
        $event=new Event();
        $form = $this->createForm(EventType::class, $event);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $event = $form->getData();

            $em=$doctrine->getManager();
            $em->persist($event);
            $em->flush();

            return $this->redirectToRoute('index');
        }

      return $this->render('event_crud/create.html.twig', [
            "form"=>$form->createView()
        ]);
    }

//  edit an event
    #[Route('/edit/{id}', name: 'edit-event')]
    public function editAction($id, Request $request, ManagerRegistry $doctrine): Response
    {
        $event=$doctrine->getRepository(Event::class)->find($id);
        $form = $this->createForm(EventType::class, $event);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $event = $form->getData();

            $em=$doctrine->getManager();
            $em->persist($event);
            $em->flush();

            return $this->redirectToRoute('index');
        }
        
        return $this->render('event_crud/edit.html.twig', [
            "form" => $form->createView(),
            "event" => $event
        ]);
    }

// details about an event 
   #[Route('/details/{id}', name: 'details-event')]
    public function detailsAction($id, ManagerRegistry $doctrine): Response
    {
        $event = $doctrine->getRepository(Event::class)->find($id);
        
        return $this->render('event_crud/details.html.twig', [
            "event" => $event
        ]);
    }

// delete a record
    #[Route('/delete/{id}', name: 'delete-event')]
    public function deleteAction(ManagerRegistry $doctrine, $id): Response
    {
        $em=$doctrine->getManager();
        $event=$doctrine->getRepository(Event::class)->find($id);
        $em->remove($event);
        $em->flush();
        return $this->redirectToRoute('index', [
        ]);
    }

// filter
#[Route('/music', name: 'filter-event1')]
public function filterAction1(ManagerRegistry $doctrine): Response
{
    $musicEvents=$doctrine->getRepository(Event:: class)->findBy(array('type'=>'music'));
   
    return $this->render('event_crud/music.html.twig', [
       "events"=>$musicEvents
    ]);
} 


#[Route('/sport', name: 'filter-event2')]
public function filterAction2(ManagerRegistry $doctrine): Response
{
    $sportEvents=$doctrine->getRepository(Event:: class)->findBy(array('type'=>'sport'));
   
    return $this->render('event_crud/sport.html.twig', [
       "events"=>$sportEvents
    ]);
} 

#[Route('/movie', name: 'filter-event3')]
public function filterAction3(ManagerRegistry $doctrine): Response
{
    $movieEvents=$doctrine->getRepository(Event:: class)->findBy(array('type'=>'movie'));
   
    return $this->render('event_crud/movie.html.twig', [
       "events"=>$movieEvents
    ]);
} 

#[Route('/miscellaneous', name: 'filter-event4')]
public function filterAction4(ManagerRegistry $doctrine): Response
{
    $difEvents=$doctrine->getRepository(Event:: class)->findBy(array('type'=>'miscellaneous'));
   
    return $this->render('event_crud/miscellaneous.html.twig', [
       "events"=>$difEvents
    ]);
} 

}

templates/event_crud/create.html.twig
{% extends "base.html.twig" %}
  {% block stylesheets %}
            <link rel="stylesheet" href="{{asset("css/createStyle.css")}}">
        {% endblock %}

{% block body %}


{# {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }} #}

<div class="container createStyle">
<h1 class="text-center m-4 text-white">Create a new event</h1>
<div class="form-control">
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}
  <div class="form-error">
        {{ form_errors(form) }}
    </div>
</div>


<a href="{{path('index')}}" class="btn btn-primary mt-4">Go back</a>
</div>


{% endblock %}

templates/event_crud/details.html.twig
{% extends "base.html.twig" %}

  {% block stylesheets %}
            <link rel="stylesheet" href="{{asset("css/createStyle.css")}}">
        {% endblock %}

{% block body %} 
<h1 class="text-white text-center m-4">More about the {{ event.name|title }}</h1>

<fieldset>
<div class="card mb-3 border-0 card1" style="max-width: 600px;">
  <img src="{{asset(event.picture)}}"  class="card-img-top text-white" alt="{{ event.name|title }}">
  <div class="card-body">
    <h5 class="card-title text-white">{{ event.name|title }} in {{ event.city|title }}</h5>
    <p class="card-text text-white">{{ event.description }}</p>
    <p class="card-text text-white">{{ event.date|date("D, d F Y g:i A") }}</p>
    <p class="card-text text-white">Location: {{ event.city|title }}</p>

    <p class="card-text"><small class="text-white">Tickets available: {{ event.capacity }}</small></p>
    <p class="card-text"><small class="text-white">Category of an event: {{ event.type }}</small></p>
    <p class="card-text"><small class="text-white">Phone Number: +{{ event.phoneNumber }}</small></p>
    <p class="card-text"><small class="text-white">Email: {{ event.email }}</small></p>
    <p class="card-text"><small class="text-white">Go to official Webpage of <a href="{{ event.url }}">{{event.name}} </a></small></p>
  </div>
</div>

</fieldset>
<a href="{{path('index')}}" class="btn btn-primary">Go back</a>
{% endblock %}

templates/event_crud/edit.html.twig
{% extends "base.html.twig" %}
  {% block stylesheets %}
            <link rel="stylesheet" href="{{asset("css/createStyle.css")}}">
        {% endblock %}
{% block body %}


<div class="container createStyle">
<h1 class="text-center m-4 text-white">Edit a record of an {{event.name}}</h1>
<div class="form-control">
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}
  <div class="form-error">
        {{ form_errors(form) }}
    </div>
</div>


<a href="{{path('index')}}" class="btn btn-primary mt-4">Go back</a>
</div>

{% endblock %}

templates/event_crud/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}All Events{% endblock %}

  {% block stylesheets %}
            <link rel="stylesheet" href="{{asset("css/events.css")}}">
        {% endblock %}
{% block body %}

<h1 class="title text-center text-white mt-4">Upcoming events</h1>

<div class="container">
<div class="text-center m-4">
<a href="" class="btn btn-primary">Music</a>
<a href="" class="btn btn-primary">Sport</a>
<a href="" class="btn btn-primary">Movie</a>
<a href="" class="btn btn-primary">Miscellaneous</a>
</div>

    <div class="row row-cols-3">
        {% for event in events %}
        <div class="card border-0 m-3  " style="width: 400px;">
            <div class="card-body">

                {# <img src="{{asset('picture/' ~ event.picture)}}" alt="" width="100%"> #}
                <img src="{{asset(event.picture)}}" alt="" width="100%">

                <h5 class="card-title text-white text-center">{{ event.name|title }} in {{ event.city|title }} </h5>
                <p class="card-text">{{ event.description }}</p>
              
                <p>{{ event.date|date("d F Y ") }}</p>
                <a href="details/{{ event.id }}" class="btn btn-success">Details</a>
                <a href="edit/{{ event.id }}" class="btn btn-warning">Edit</a>
                <a href="delete/{{ event.id }}" class="btn btn-danger">Delete</a>

               
            </div>
        </div>


         {% else %}
           <h3 class="text-center">There are no upcoming events</h3>
        {% endfor %}
    </div>
</div>
{% endblock %}

 

templates/event_crud/miscellaneous.html.twig
{% extends 'base.html.twig' %}

{% block title %}Miscellaneous Events{% endblock %}

  {% block stylesheets %}
            <link rel="stylesheet" href="{{asset("css/events.css")}}">
        {% endblock %}
{% block body %}

<h1 class="title text-center text-white mt-4">Miscellaneous events</h1>

<div class="container">


    <div class="row row-cols-3">
        {% for event in events %}
        <div class="card border-0 m-3  " style="width: 400px;">
            <div class="card-body">

                {# <img src="{{asset('picture/' ~ event.picture)}}" alt="" width="100%"> #}
                <img src="{{asset(event.picture)}}" alt="" width="100%">

                <h5 class="card-title text-white text-center">{{ event.name|title }} in {{ event.city|title }} </h5>
                <p class="card-text">{{ event.description }}</p>
              
                <p>{{ event.date|date("d F Y ") }}</p>
                <a href="details/{{ event.id }}" class="btn btn-success">Details</a>
                <a href="edit/{{ event.id }}" class="btn btn-warning">Edit</a>
                <a href="delete/{{ event.id }}" class="btn btn-danger">Delete</a>

               
            </div>
        </div>


         {% else %}
           <h3 class="text-center">There are no upcoming events</h3>
        {% endfor %}
    </div>
    <a href="{{path('index')}}" class="btn btn-primary">Go back</a>

</div>
{% endblock %}

 

templates/event_crud/movie.html.twig
{% extends 'base.html.twig' %}

{% block title %}Movies Events{% endblock %}

  {% block stylesheets %}
            <link rel="stylesheet" href="{{asset("css/events.css")}}">
        {% endblock %}
{% block body %}

<h1 class="title text-center text-white mt-4">Movies events</h1>

<div class="container">


    <div class="row row-cols-3">
        {% for event in events %}
        <div class="card border-0 m-3  " style="width: 400px;">
            <div class="card-body">

                {# <img src="{{asset('picture/' ~ event.picture)}}" alt="" width="100%"> #}
                <img src="{{asset(event.picture)}}" alt="" width="100%">

                <h5 class="card-title text-white text-center">{{ event.name|title }} in {{ event.city|title }} </h5>
                <p class="card-text">{{ event.description }}</p>
              
                <p>{{ event.date|date("d F Y ") }}</p>
                <a href="details/{{ event.id }}" class="btn btn-success">Details</a>
                <a href="edit/{{ event.id }}" class="btn btn-warning">Edit</a>
                <a href="delete/{{ event.id }}" class="btn btn-danger">Delete</a>

               
            </div>
        </div>


         {% else %}
           <h3 class="text-center">There are no upcoming events</h3>
        {% endfor %}
    </div>
    <a href="{{path('index')}}" class="btn btn-primary">Go back</a>

</div>
{% endblock %}

 

templates/event_crud/music.html.twig
{% extends 'base.html.twig' %}

{% block title %}Music Events{% endblock %}

  {% block stylesheets %}
            <link rel="stylesheet" href="{{asset("css/events.css")}}">
        {% endblock %}
{% block body %}

<h1 class="title text-center text-white mt-4">Music events</h1>

<div class="container">


    <div class="row row-cols-3">
        {% for event in events %}
        <div class="card border-0 m-3  " style="width: 400px;">
            <div class="card-body">

                {# <img src="{{asset('picture/' ~ event.picture)}}" alt="" width="100%"> #}
                <img src="{{asset(event.picture)}}" alt="" width="100%">

                <h5 class="card-title text-white text-center">{{ event.name|title }} in {{ event.city|title }} </h5>
                <p class="card-text">{{ event.description }}</p>
              
                <p>{{ event.date|date("d F Y ") }}</p>
                <a href="details/{{ event.id }}" class="btn btn-success">Details</a>
                <a href="edit/{{ event.id }}" class="btn btn-warning">Edit</a>
                <a href="delete/{{ event.id }}" class="btn btn-danger">Delete</a>

               
            </div>
        </div>


         {% else %}
           <h3 class="text-center">There are no upcoming events</h3>
        {% endfor %}
    </div>
    <a href="{{path('index')}}" class="btn btn-primary">Go back</a>

</div>
{% endblock %}

 

templates/event_crud/sport.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sport Events{% endblock %}

  {% block stylesheets %}
            <link rel="stylesheet" href="{{asset("css/events.css")}}">
        {% endblock %}
{% block body %}

<h1 class="title text-center text-white mt-4">Sport events</h1>

<div class="container">


    <div class="row row-cols-3">
        {% for event in events %}
        <div class="card border-0 m-3  " style="width: 400px;">
            <div class="card-body">

                {# <img src="{{asset('picture/' ~ event.picture)}}" alt="" width="100%"> #}
                <img src="{{asset(event.picture)}}" alt="" width="100%">

                <h5 class="card-title text-white text-center">{{ event.name|title }} in {{ event.city|title }} </h5>
                <p class="card-text">{{ event.description }}</p>
              
                <p>{{ event.date|date("d F Y ") }}</p>
                <a href="details/{{ event.id }}" class="btn btn-success">Details</a>
                <a href="edit/{{ event.id }}" class="btn btn-warning">Edit</a>
                <a href="delete/{{ event.id }}" class="btn btn-danger">Delete</a>

               
            </div>
        </div>


         {% else %}
           <h3 class="text-center">There are no upcoming events</h3>
        {% endfor %}
    </div>
    <a href="{{path('index')}}" class="btn btn-primary">Go back</a>

</div>
{% endblock %}

 